/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedParametresProfilRouteImport } from './routes/_authenticated/parametres/profil'
import { Route as AuthenticatedParametresAbonnementRouteImport } from './routes/_authenticated/parametres/abonnement'
import { Route as AuthenticatedEvaluationsEnregistrerRouteImport } from './routes/_authenticated/evaluations/enregistrer'
import { Route as AuthenticatedElevesMesElevesRouteImport } from './routes/_authenticated/eleves/mes-eleves'
import { Route as AuthenticatedElevesCreerEleveRouteImport } from './routes/_authenticated/eleves/creer-eleve'
import { Route as AuthenticatedClassesMesClassesRouteImport } from './routes/_authenticated/classes/mes-classes'
import { Route as AuthenticatedClassesCreerUneClasseRouteImport } from './routes/_authenticated/classes/creer-une-classe'
import { Route as AuthenticatedClassesClassNameRouteImport } from './routes/_authenticated/classes/$className'
import { Route as AuthenticatedClassesClassNameIndexRouteImport } from './routes/_authenticated/classes/$className/index'
import { Route as AuthenticatedClassesClassNameStudentNameRouteImport } from './routes/_authenticated/classes/$className/$studentName'
import { Route as AuthenticatedClassesClassNameEvaluationIndexRouteImport } from './routes/_authenticated/classes/$className/evaluation/index'
import { Route as AuthenticatedClassesClassNameEvaluationEvaluationNameRouteImport } from './routes/_authenticated/classes/$className/evaluation/$evaluationName'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParametresProfilRoute =
  AuthenticatedParametresProfilRouteImport.update({
    id: '/parametres/profil',
    path: '/parametres/profil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParametresAbonnementRoute =
  AuthenticatedParametresAbonnementRouteImport.update({
    id: '/parametres/abonnement',
    path: '/parametres/abonnement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEvaluationsEnregistrerRoute =
  AuthenticatedEvaluationsEnregistrerRouteImport.update({
    id: '/evaluations/enregistrer',
    path: '/evaluations/enregistrer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedElevesMesElevesRoute =
  AuthenticatedElevesMesElevesRouteImport.update({
    id: '/eleves/mes-eleves',
    path: '/eleves/mes-eleves',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedElevesCreerEleveRoute =
  AuthenticatedElevesCreerEleveRouteImport.update({
    id: '/eleves/creer-eleve',
    path: '/eleves/creer-eleve',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesMesClassesRoute =
  AuthenticatedClassesMesClassesRouteImport.update({
    id: '/classes/mes-classes',
    path: '/classes/mes-classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesCreerUneClasseRoute =
  AuthenticatedClassesCreerUneClasseRouteImport.update({
    id: '/classes/creer-une-classe',
    path: '/classes/creer-une-classe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassNameRoute =
  AuthenticatedClassesClassNameRouteImport.update({
    id: '/classes/$className',
    path: '/classes/$className',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassNameIndexRoute =
  AuthenticatedClassesClassNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassesClassNameRoute,
  } as any)
const AuthenticatedClassesClassNameStudentNameRoute =
  AuthenticatedClassesClassNameStudentNameRouteImport.update({
    id: '/$studentName',
    path: '/$studentName',
    getParentRoute: () => AuthenticatedClassesClassNameRoute,
  } as any)
const AuthenticatedClassesClassNameEvaluationIndexRoute =
  AuthenticatedClassesClassNameEvaluationIndexRouteImport.update({
    id: '/evaluation/',
    path: '/evaluation/',
    getParentRoute: () => AuthenticatedClassesClassNameRoute,
  } as any)
const AuthenticatedClassesClassNameEvaluationEvaluationNameRoute =
  AuthenticatedClassesClassNameEvaluationEvaluationNameRouteImport.update({
    id: '/evaluation/$evaluationName',
    path: '/evaluation/$evaluationName',
    getParentRoute: () => AuthenticatedClassesClassNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/': typeof PublicIndexRoute
  '/classes/$className': typeof AuthenticatedClassesClassNameRouteWithChildren
  '/classes/creer-une-classe': typeof AuthenticatedClassesCreerUneClasseRoute
  '/classes/mes-classes': typeof AuthenticatedClassesMesClassesRoute
  '/eleves/creer-eleve': typeof AuthenticatedElevesCreerEleveRoute
  '/eleves/mes-eleves': typeof AuthenticatedElevesMesElevesRoute
  '/evaluations/enregistrer': typeof AuthenticatedEvaluationsEnregistrerRoute
  '/parametres/abonnement': typeof AuthenticatedParametresAbonnementRoute
  '/parametres/profil': typeof AuthenticatedParametresProfilRoute
  '/classes/$className/$studentName': typeof AuthenticatedClassesClassNameStudentNameRoute
  '/classes/$className/': typeof AuthenticatedClassesClassNameIndexRoute
  '/classes/$className/evaluation/$evaluationName': typeof AuthenticatedClassesClassNameEvaluationEvaluationNameRoute
  '/classes/$className/evaluation': typeof AuthenticatedClassesClassNameEvaluationIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/': typeof PublicIndexRoute
  '/classes/creer-une-classe': typeof AuthenticatedClassesCreerUneClasseRoute
  '/classes/mes-classes': typeof AuthenticatedClassesMesClassesRoute
  '/eleves/creer-eleve': typeof AuthenticatedElevesCreerEleveRoute
  '/eleves/mes-eleves': typeof AuthenticatedElevesMesElevesRoute
  '/evaluations/enregistrer': typeof AuthenticatedEvaluationsEnregistrerRoute
  '/parametres/abonnement': typeof AuthenticatedParametresAbonnementRoute
  '/parametres/profil': typeof AuthenticatedParametresProfilRoute
  '/classes/$className/$studentName': typeof AuthenticatedClassesClassNameStudentNameRoute
  '/classes/$className': typeof AuthenticatedClassesClassNameIndexRoute
  '/classes/$className/evaluation/$evaluationName': typeof AuthenticatedClassesClassNameEvaluationEvaluationNameRoute
  '/classes/$className/evaluation': typeof AuthenticatedClassesClassNameEvaluationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/classes/$className': typeof AuthenticatedClassesClassNameRouteWithChildren
  '/_authenticated/classes/creer-une-classe': typeof AuthenticatedClassesCreerUneClasseRoute
  '/_authenticated/classes/mes-classes': typeof AuthenticatedClassesMesClassesRoute
  '/_authenticated/eleves/creer-eleve': typeof AuthenticatedElevesCreerEleveRoute
  '/_authenticated/eleves/mes-eleves': typeof AuthenticatedElevesMesElevesRoute
  '/_authenticated/evaluations/enregistrer': typeof AuthenticatedEvaluationsEnregistrerRoute
  '/_authenticated/parametres/abonnement': typeof AuthenticatedParametresAbonnementRoute
  '/_authenticated/parametres/profil': typeof AuthenticatedParametresProfilRoute
  '/_authenticated/classes/$className/$studentName': typeof AuthenticatedClassesClassNameStudentNameRoute
  '/_authenticated/classes/$className/': typeof AuthenticatedClassesClassNameIndexRoute
  '/_authenticated/classes/$className/evaluation/$evaluationName': typeof AuthenticatedClassesClassNameEvaluationEvaluationNameRoute
  '/_authenticated/classes/$className/evaluation/': typeof AuthenticatedClassesClassNameEvaluationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/'
    | '/classes/$className'
    | '/classes/creer-une-classe'
    | '/classes/mes-classes'
    | '/eleves/creer-eleve'
    | '/eleves/mes-eleves'
    | '/evaluations/enregistrer'
    | '/parametres/abonnement'
    | '/parametres/profil'
    | '/classes/$className/$studentName'
    | '/classes/$className/'
    | '/classes/$className/evaluation/$evaluationName'
    | '/classes/$className/evaluation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/'
    | '/classes/creer-une-classe'
    | '/classes/mes-classes'
    | '/eleves/creer-eleve'
    | '/eleves/mes-eleves'
    | '/evaluations/enregistrer'
    | '/parametres/abonnement'
    | '/parametres/profil'
    | '/classes/$className/$studentName'
    | '/classes/$className'
    | '/classes/$className/evaluation/$evaluationName'
    | '/classes/$className/evaluation'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/login'
    | '/_public/signup'
    | '/_public/'
    | '/_authenticated/classes/$className'
    | '/_authenticated/classes/creer-une-classe'
    | '/_authenticated/classes/mes-classes'
    | '/_authenticated/eleves/creer-eleve'
    | '/_authenticated/eleves/mes-eleves'
    | '/_authenticated/evaluations/enregistrer'
    | '/_authenticated/parametres/abonnement'
    | '/_authenticated/parametres/profil'
    | '/_authenticated/classes/$className/$studentName'
    | '/_authenticated/classes/$className/'
    | '/_authenticated/classes/$className/evaluation/$evaluationName'
    | '/_authenticated/classes/$className/evaluation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres/profil': {
      id: '/_authenticated/parametres/profil'
      path: '/parametres/profil'
      fullPath: '/parametres/profil'
      preLoaderRoute: typeof AuthenticatedParametresProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres/abonnement': {
      id: '/_authenticated/parametres/abonnement'
      path: '/parametres/abonnement'
      fullPath: '/parametres/abonnement'
      preLoaderRoute: typeof AuthenticatedParametresAbonnementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evaluations/enregistrer': {
      id: '/_authenticated/evaluations/enregistrer'
      path: '/evaluations/enregistrer'
      fullPath: '/evaluations/enregistrer'
      preLoaderRoute: typeof AuthenticatedEvaluationsEnregistrerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eleves/mes-eleves': {
      id: '/_authenticated/eleves/mes-eleves'
      path: '/eleves/mes-eleves'
      fullPath: '/eleves/mes-eleves'
      preLoaderRoute: typeof AuthenticatedElevesMesElevesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eleves/creer-eleve': {
      id: '/_authenticated/eleves/creer-eleve'
      path: '/eleves/creer-eleve'
      fullPath: '/eleves/creer-eleve'
      preLoaderRoute: typeof AuthenticatedElevesCreerEleveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/mes-classes': {
      id: '/_authenticated/classes/mes-classes'
      path: '/classes/mes-classes'
      fullPath: '/classes/mes-classes'
      preLoaderRoute: typeof AuthenticatedClassesMesClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/creer-une-classe': {
      id: '/_authenticated/classes/creer-une-classe'
      path: '/classes/creer-une-classe'
      fullPath: '/classes/creer-une-classe'
      preLoaderRoute: typeof AuthenticatedClassesCreerUneClasseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$className': {
      id: '/_authenticated/classes/$className'
      path: '/classes/$className'
      fullPath: '/classes/$className'
      preLoaderRoute: typeof AuthenticatedClassesClassNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$className/': {
      id: '/_authenticated/classes/$className/'
      path: '/'
      fullPath: '/classes/$className/'
      preLoaderRoute: typeof AuthenticatedClassesClassNameIndexRouteImport
      parentRoute: typeof AuthenticatedClassesClassNameRoute
    }
    '/_authenticated/classes/$className/$studentName': {
      id: '/_authenticated/classes/$className/$studentName'
      path: '/$studentName'
      fullPath: '/classes/$className/$studentName'
      preLoaderRoute: typeof AuthenticatedClassesClassNameStudentNameRouteImport
      parentRoute: typeof AuthenticatedClassesClassNameRoute
    }
    '/_authenticated/classes/$className/evaluation/': {
      id: '/_authenticated/classes/$className/evaluation/'
      path: '/evaluation'
      fullPath: '/classes/$className/evaluation'
      preLoaderRoute: typeof AuthenticatedClassesClassNameEvaluationIndexRouteImport
      parentRoute: typeof AuthenticatedClassesClassNameRoute
    }
    '/_authenticated/classes/$className/evaluation/$evaluationName': {
      id: '/_authenticated/classes/$className/evaluation/$evaluationName'
      path: '/evaluation/$evaluationName'
      fullPath: '/classes/$className/evaluation/$evaluationName'
      preLoaderRoute: typeof AuthenticatedClassesClassNameEvaluationEvaluationNameRouteImport
      parentRoute: typeof AuthenticatedClassesClassNameRoute
    }
  }
}

interface AuthenticatedClassesClassNameRouteChildren {
  AuthenticatedClassesClassNameStudentNameRoute: typeof AuthenticatedClassesClassNameStudentNameRoute
  AuthenticatedClassesClassNameIndexRoute: typeof AuthenticatedClassesClassNameIndexRoute
  AuthenticatedClassesClassNameEvaluationEvaluationNameRoute: typeof AuthenticatedClassesClassNameEvaluationEvaluationNameRoute
  AuthenticatedClassesClassNameEvaluationIndexRoute: typeof AuthenticatedClassesClassNameEvaluationIndexRoute
}

const AuthenticatedClassesClassNameRouteChildren: AuthenticatedClassesClassNameRouteChildren =
  {
    AuthenticatedClassesClassNameStudentNameRoute:
      AuthenticatedClassesClassNameStudentNameRoute,
    AuthenticatedClassesClassNameIndexRoute:
      AuthenticatedClassesClassNameIndexRoute,
    AuthenticatedClassesClassNameEvaluationEvaluationNameRoute:
      AuthenticatedClassesClassNameEvaluationEvaluationNameRoute,
    AuthenticatedClassesClassNameEvaluationIndexRoute:
      AuthenticatedClassesClassNameEvaluationIndexRoute,
  }

const AuthenticatedClassesClassNameRouteWithChildren =
  AuthenticatedClassesClassNameRoute._addFileChildren(
    AuthenticatedClassesClassNameRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClassesClassNameRoute: typeof AuthenticatedClassesClassNameRouteWithChildren
  AuthenticatedClassesCreerUneClasseRoute: typeof AuthenticatedClassesCreerUneClasseRoute
  AuthenticatedClassesMesClassesRoute: typeof AuthenticatedClassesMesClassesRoute
  AuthenticatedElevesCreerEleveRoute: typeof AuthenticatedElevesCreerEleveRoute
  AuthenticatedElevesMesElevesRoute: typeof AuthenticatedElevesMesElevesRoute
  AuthenticatedEvaluationsEnregistrerRoute: typeof AuthenticatedEvaluationsEnregistrerRoute
  AuthenticatedParametresAbonnementRoute: typeof AuthenticatedParametresAbonnementRoute
  AuthenticatedParametresProfilRoute: typeof AuthenticatedParametresProfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClassesClassNameRoute:
    AuthenticatedClassesClassNameRouteWithChildren,
  AuthenticatedClassesCreerUneClasseRoute:
    AuthenticatedClassesCreerUneClasseRoute,
  AuthenticatedClassesMesClassesRoute: AuthenticatedClassesMesClassesRoute,
  AuthenticatedElevesCreerEleveRoute: AuthenticatedElevesCreerEleveRoute,
  AuthenticatedElevesMesElevesRoute: AuthenticatedElevesMesElevesRoute,
  AuthenticatedEvaluationsEnregistrerRoute:
    AuthenticatedEvaluationsEnregistrerRoute,
  AuthenticatedParametresAbonnementRoute:
    AuthenticatedParametresAbonnementRoute,
  AuthenticatedParametresProfilRoute: AuthenticatedParametresProfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
